### PR TITLE
Support servant in new package core-webserver-servant

### PR DESCRIPTION
**Pull request by carlosdagos**
Add support for servant ServerT monads based on Program.

The important part is that it leverages the wai Request "vault"
to carry the context containing the necessary trace and span data
so that we can trace handlers per-request.

### CODE REVIEW

**Comment by carlosdagos** [comment]
Draft PR pending more documentation.

**Comment by istathar** [comment]
Hm. So you think `launchServantRoutes` should call `launchWebserver`.

I'm more inclined to have a helper function returns an Application that then gets passed by the user to `launchWebserver`. Having it all be magic is cool sometimes, but our principal complaint with **servant** is that it hides too much under the hood.

I think it might be best if we change it to
```
prepareRoutes :: ... -> Program t Application 
```

The usage would then be

```
execute $ do
    application <- prepareRoutes ...
    launchWebserver port application
```

**Comment by istathar** [comment]
@carlosdagos I can't make sense of why the CI is failing. `stack test` there should be the same as `stack test` here; it's the same _stack.yaml_ file, after all, but with modern **aeson** it still builds. When **servant** does a new release the problem will go away, but for now... Maybe I'll just drop the aeson >= 2  from the _stack.yaml_ in this repo which its testing against. We know our code works both ways.

**Comment by istathar** [comment]
This needs a bit more work to get up to the standard of the other packages in the collection, but I think it's good enough to put up on Hackage so at least we can use it without having to much around with Git references in people's _stack.yaml_. It's marked `experimental` so up they go.

Remaining items

- [ ] Improve the module documentation Haddock example showing a Servant API.
- [ ] Proper test suite coverage

**Comment by istathar** [comment]
Oh, found a bug. We _don't_ need to propagate the HTTP metrics (`request.path`, etc) to the child spans. We'll need a `clearMetrics` or something in **core-telemetry**. I'll add that this afternoon.

**Comment by istathar** [comment]
Done in a8427eb5e0e484edcefc45b878dc11b9206b48b5. It's a little fragile. Perhaps we should be forking the telemetry state before descending into the child handler. I'll think about it. Anyway, sorted for now.

**Pull request merged**
